# Meta Data for SEO

## Open Graph + Twitter Cards
images = ["finec-mgimo-footer.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "ru_RU"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/h-enk"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
# footer = "Факультет финансовой экономики МГИМО"

# Alert
alert = true
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/finec-mgimo/finec-mgimo.github.io"
editPage = false

[options]
lazySizes = true
clipBoard = true
instantPage = true
flexSearch = true
darkMode = false
bootStrapJs = false
breadCrumb = false
highLight = true
kaTex = false
